version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: portaria_postgres
    restart: always
    environment:
      POSTGRES_USER: portaria
      POSTGRES_PASSWORD: portaria123
      POSTGRES_DB: portaria_saas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
